kind: ReplicationController
apiVersion: v1
metadata:
  name: __rcName__
  labels: &labels
    name: __rcName__
    major: "__major__"
    minor: "__minor__"
    build: "__build__"

spec:
  replicas: __replicas__
  selector: *labels
  template:
    metadata:
      name: __rcName__
      labels: *labels

    spec:
      containers:
        - name: __rcName__
          image: __image__
          ports:
             - name: __privatePortName__
               containerPort: __privatePort__
